---
name: Deploy Website with Surge

on:
  push:
    branches:
      - master


jobs:
  - name: Upload a Build Artifact
  uses: actions/upload-artifact@v2
  uses: actions/checkout@v2
  - name: Setup Node
  uses: actions/setup-node@v2-beta
  with:
    node-version: '12'
  - name: Setup Surge
  run: npm install --global Surge
  - name: execute Deployment with Surge
  run: surge ./ Web-dev-proj.surge.sh --token {{secrets.WEB_DEV_PROJECT_SURGE_TOKEN}}

