---
name: Deploy Website with Surge

on:
  push:
    branches:
      - master


jobs:
  build:
    name: Job_Deploy_Surge
    runs-on: ubuntu-latest
    steps:  
    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Setup Surge
      run: npm install --global surge
    - name: execute Deployment with Surge
      run: surge ./ Web-dev-proj.surge.sh --token ${{secrets.web_dev_project_surge_token}}
        

